<?php
/**
 * Quota
 *
 * PHP version 5
 *
 * @category Class
 * @package  ExaVault
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ExaVault\Model;

use \ArrayAccess;
use \ExaVault\ObjectSerializer;

/**
 * Quota Class Doc Comment
 *
 * @category Class
 * @package  ExaVault
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Quota implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Quota';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'diskLimit' => 'int',
'diskUsed' => 'int',
'noticeEnabled' => 'bool',
'noticeThreshold' => 'int',
'bandwidthLimit' => 'int',
'bandwidthUsed' => 'int',
'transactionsLimit' => 'int',
'transactionsNoticeEnabled' => 'bool',
'transactionsNoticeThreshold' => 'int'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'diskLimit' => 'int64',
'diskUsed' => 'int64',
'noticeEnabled' => null,
'noticeThreshold' => 'int32',
'bandwidthLimit' => 'int64',
'bandwidthUsed' => 'int64',
'transactionsLimit' => 'int32',
'transactionsNoticeEnabled' => null,
'transactionsNoticeThreshold' => 'int32'    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'diskLimit' => 'diskLimit',
'diskUsed' => 'diskUsed',
'noticeEnabled' => 'noticeEnabled',
'noticeThreshold' => 'noticeThreshold',
'bandwidthLimit' => 'bandwidthLimit',
'bandwidthUsed' => 'bandwidthUsed',
'transactionsLimit' => 'transactionsLimit',
'transactionsNoticeEnabled' => 'transactionsNoticeEnabled',
'transactionsNoticeThreshold' => 'transactionsNoticeThreshold'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'diskLimit' => 'setDiskLimit',
'diskUsed' => 'setDiskUsed',
'noticeEnabled' => 'setNoticeEnabled',
'noticeThreshold' => 'setNoticeThreshold',
'bandwidthLimit' => 'setBandwidthLimit',
'bandwidthUsed' => 'setBandwidthUsed',
'transactionsLimit' => 'setTransactionsLimit',
'transactionsNoticeEnabled' => 'setTransactionsNoticeEnabled',
'transactionsNoticeThreshold' => 'setTransactionsNoticeThreshold'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'diskLimit' => 'getDiskLimit',
'diskUsed' => 'getDiskUsed',
'noticeEnabled' => 'getNoticeEnabled',
'noticeThreshold' => 'getNoticeThreshold',
'bandwidthLimit' => 'getBandwidthLimit',
'bandwidthUsed' => 'getBandwidthUsed',
'transactionsLimit' => 'getTransactionsLimit',
'transactionsNoticeEnabled' => 'getTransactionsNoticeEnabled',
'transactionsNoticeThreshold' => 'getTransactionsNoticeThreshold'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['diskLimit'] = isset($data['diskLimit']) ? $data['diskLimit'] : null;
        $this->container['diskUsed'] = isset($data['diskUsed']) ? $data['diskUsed'] : null;
        $this->container['noticeEnabled'] = isset($data['noticeEnabled']) ? $data['noticeEnabled'] : null;
        $this->container['noticeThreshold'] = isset($data['noticeThreshold']) ? $data['noticeThreshold'] : null;
        $this->container['bandwidthLimit'] = isset($data['bandwidthLimit']) ? $data['bandwidthLimit'] : null;
        $this->container['bandwidthUsed'] = isset($data['bandwidthUsed']) ? $data['bandwidthUsed'] : null;
        $this->container['transactionsLimit'] = isset($data['transactionsLimit']) ? $data['transactionsLimit'] : null;
        $this->container['transactionsNoticeEnabled'] = isset($data['transactionsNoticeEnabled']) ? $data['transactionsNoticeEnabled'] : null;
        $this->container['transactionsNoticeThreshold'] = isset($data['transactionsNoticeThreshold']) ? $data['transactionsNoticeThreshold'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets diskLimit
     *
     * @return int
     */
    public function getDiskLimit()
    {
        return $this->container['diskLimit'];
    }

    /**
     * Sets diskLimit
     *
     * @param int $diskLimit Amount of disk space that the account has available to it. This may be increased by upgrading to a larger plan.
     *
     * @return $this
     */
    public function setDiskLimit($diskLimit)
    {
        $this->container['diskLimit'] = $diskLimit;

        return $this;
    }

    /**
     * Gets diskUsed
     *
     * @return int
     */
    public function getDiskUsed()
    {
        return $this->container['diskUsed'];
    }

    /**
     * Sets diskUsed
     *
     * @param int $diskUsed Amount of disk space currently in use.
     *
     * @return $this
     */
    public function setDiskUsed($diskUsed)
    {
        $this->container['diskUsed'] = $diskUsed;

        return $this;
    }

    /**
     * Gets noticeEnabled
     *
     * @return bool
     */
    public function getNoticeEnabled()
    {
        return $this->container['noticeEnabled'];
    }

    /**
     * Sets noticeEnabled
     *
     * @param bool $noticeEnabled Should a quota warning be sent to the account owner when a threshold level of space utilization is reached?
     *
     * @return $this
     */
    public function setNoticeEnabled($noticeEnabled)
    {
        $this->container['noticeEnabled'] = $noticeEnabled;

        return $this;
    }

    /**
     * Gets noticeThreshold
     *
     * @return int
     */
    public function getNoticeThreshold()
    {
        return $this->container['noticeThreshold'];
    }

    /**
     * Sets noticeThreshold
     *
     * @param int $noticeThreshold Treshold that triggers a quota notification. This represents the \"percent full\" your account must be before the quota notification is generated.
     *
     * @return $this
     */
    public function setNoticeThreshold($noticeThreshold)
    {
        $this->container['noticeThreshold'] = $noticeThreshold;

        return $this;
    }

    /**
     * Gets bandwidthLimit
     *
     * @return int
     */
    public function getBandwidthLimit()
    {
        return $this->container['bandwidthLimit'];
    }

    /**
     * Sets bandwidthLimit
     *
     * @param int $bandwidthLimit Total number of bytes that can be transferred per month.
     *
     * @return $this
     */
    public function setBandwidthLimit($bandwidthLimit)
    {
        $this->container['bandwidthLimit'] = $bandwidthLimit;

        return $this;
    }

    /**
     * Gets bandwidthUsed
     *
     * @return int
     */
    public function getBandwidthUsed()
    {
        return $this->container['bandwidthUsed'];
    }

    /**
     * Sets bandwidthUsed
     *
     * @param int $bandwidthUsed Number of bytes transferred this month.
     *
     * @return $this
     */
    public function setBandwidthUsed($bandwidthUsed)
    {
        $this->container['bandwidthUsed'] = $bandwidthUsed;

        return $this;
    }

    /**
     * Gets transactionsLimit
     *
     * @return int
     */
    public function getTransactionsLimit()
    {
        return $this->container['transactionsLimit'];
    }

    /**
     * Sets transactionsLimit
     *
     * @param int $transactionsLimit Total number of transactions allowed in a 24-hour period.
     *
     * @return $this
     */
    public function setTransactionsLimit($transactionsLimit)
    {
        $this->container['transactionsLimit'] = $transactionsLimit;

        return $this;
    }

    /**
     * Gets transactionsNoticeEnabled
     *
     * @return bool
     */
    public function getTransactionsNoticeEnabled()
    {
        return $this->container['transactionsNoticeEnabled'];
    }

    /**
     * Sets transactionsNoticeEnabled
     *
     * @param bool $transactionsNoticeEnabled Whether an email should be sent to the account owner up to once per day if transaction usage exceeds `transactionsNoticeThreshold` value.
     *
     * @return $this
     */
    public function setTransactionsNoticeEnabled($transactionsNoticeEnabled)
    {
        $this->container['transactionsNoticeEnabled'] = $transactionsNoticeEnabled;

        return $this;
    }

    /**
     * Gets transactionsNoticeThreshold
     *
     * @return int
     */
    public function getTransactionsNoticeThreshold()
    {
        return $this->container['transactionsNoticeThreshold'];
    }

    /**
     * Sets transactionsNoticeThreshold
     *
     * @param int $transactionsNoticeThreshold Percent of daily transactions limit that will trigger an email if activity exceeds it.
     *
     * @return $this
     */
    public function setTransactionsNoticeThreshold($transactionsNoticeThreshold)
    {
        $this->container['transactionsNoticeThreshold'] = $transactionsNoticeThreshold;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
